services:
  embassy-bot:
    build: .
    container_name: selenium-bot
    environment:
      - SE_OPTS=--headless --no-sandbox --disable-dev-shm-usage --disable-gpu
      - TZ=Europe/Moscow
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
