version: '3'

services:
  selenium-bot:
    build: .
    container_name: selenium-bot
    environment:
      - SE_OPTS=--headless --no-sandbox --disable-dev-shm-usage --disable-gpu
      - TZ=Europe/Moscow
    volumes:
      - ./logs:/app/logs  # Для сохранения логов
      - ./src:/app/src